### ISSUE TITLE
Cho tui link tải

### ISSUE THREAD

**Issue by maiminhdung** [KurumiFake/AmongCord#2]
.

**Comment by KurumiFake** [comment]
https://github.com/KurumiFake/AmongCord/actions , cái mới nhất.
![image](https://user-images.githubusercontent.com/86518350/158015102-ed55965b-4f1b-4b19-ae98-89fd733787fd.png)
ít literally that button lol

**Comment by KurumiFake** [comment]
its*

**Comment by KurumiFake** [comment]
44a70f593235f80c923289892a7d375bb58aa3cf'd, enjoy
